### ISSUE TITLE
mod slow down osTicket 1.9.3

### ISSUE THREAD

**Issue by liebendkl** [rowlandan25/osTicket-Modules#4] opened 2014-08-14 13:31 UTC
Hi, after module initialisation "ticket list view" starts to load very slow, it take few minutes to show all tickets: one by one

all module features work fine!!!! Thank you

Version 1.9.3 (test installation, not clear)

**Comment by rowlandan25** [comment] 2014-08-14 13:36
Do you get any errors in the System Log?  I am especially curious about any SQL errors.  If you do have  any, please post them.

**Comment by liebendkl** [comment] 2014-08-14 13:38
OO, sorry, soon v1.9.3-1005 (alpha) my osticket back to normal speed

**Comment by rowlandan25** [comment] 2014-08-14 13:40
Awesome, the problem was caused by the bug fixed in build 1005.

**Comment by liebendkl** [comment] 2014-08-14 13:40
[SELECT propertyName, valueCurrent FROM os_mod_status_object_properties WHERE objectId=1]

Table 'db532129552.os_mod_status_object_properties' doesn't exist<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(169): osTicket->logDBError('DB Error #1146', '[SELECT propert...')<br />
#1 (root)/include/staff/tickets.inc.php(449): db_query('SELECT property...')<br />
#2 (root)/scp/tickets.php(637): require_once('/homepages/40/d...')<br />
#3 (root)/scp/index.php(17): require('/homepages/40/d...')<br />
#4 {main}

**Closed as completed by rowlandan25** 2014-08-14 13:40 UTC
