### ISSUE TITLE
Changing Status Color

### ISSUE THREAD

**Issue by johnhwyman** [rowlandan25/osTicket-Modules#15] opened 2014-11-18 22:10 UTC
When I change the colors for Open, it changes all the other status items that haven't yet been assigned a color. Maybe they need a default color assigned when creating them.

**Comment by rowlandan25** [comment] 2014-11-19 12:31
The colors are not actually being assigned to those without.  The problem is if there is no color assigned, it was using the previous status's colors.  I am adding logic to clear the variable in the loop so this doesn't happen in the future.

**Comment by rowlandan25** [comment] 2014-11-19 13:26
Fix is implemented into Build 1009.

**Closed as completed** 2014-11-19 13:59 UTC
Labels: bug
